mysite/dysk/urls.py
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib import admin

from . import views

urlpatterns=[
    path('', views.profile, name='profile'),
    path('error', views.error, name='error'),
    path('about', views.about, name='about'),
    path('profile', views.profile, name='profile'),
    path('addCatalog/<int:disk_id>/',views.addCatalog, name='addCatalog'),
    path('addCatalog/',views.addCatalog, name='addCatalog'),
    path('deleteCatalog/<int:catalog_id>/',views.deleteCatalog, name='deleteCatalog'),
    path('deleteCatalog/',views.deleteCatalog, name='deleteCatalog'),
    path('addStandard/<int:user_id>/',views.addStandard, name='addStandard'),
    path('addStandard',views.addStandard, name='addStandard'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('disk/<int:disk_id>/',views.disk, name='disk'),
    path('disk/',views.disk, name='disk'),
    path('diskDelete/<int:disk_id>/',views.diskDelete, name='diskDelete'),
    path('diskDelete/',views.diskDelete, name='diskDelete'),
    path('catalog/<int:disk_id>/<int:catalog_id>/',views.catalog, name='catalog'),
    path('catalog/<int:disk_id>/<int:catalog_nadrzedny_id>/<int:catalog_id>>', views.catalog, name='catalog'),
    path('catalog/',views.catalog, name='catalog'),
    path('upload/<int:disk_id>/<int:catalog_id>/', views.upload, name='upload'),
    path('upload/',views.disk, name='upload'),
    path('deleteFile/<int:plik_id>/',views.deleteFile, name='deleteFile'),
    path('deleteFile/',views.deleteFile, name='deleteFile'),
    path('addCatalogNadrzedny/<int:disk_id>/<int:catalog_id>', views.addCatalogNadrzedny, name='addCatalogNadrzedny'),
    path('addCatalogNadrzedny/', views.addCatalogNadrzedny, name='addCatalogNadrzedny'),
    path('catalogNadrzedny/<int:disk_id>/<int:catalog_id>/<int:catalog>', views.catalogNadrzedny, name='CatalogNadrzedny'),
    path('catalogNadrzedny/', views.catalogNadrzedny, name='CatalogNadrzedny'),
    path('changeNameFolder/<int:disk_id>/<int:folder_id>/', views.changeNameFolder, name='changeNameFolder'),
    path('changeNameFolder/', views.changeNameFolder, name='changeNameFolder'),
    path('copyFile/<int:catalog_id>/<int:plik_id>/', views.copyFile, name='copyFile'),
    path('copyFile/', views.copyFile, name='copyFile'),
    path('cutFile/<int:catalog_id>/<int:plik_id>/', views.cutFile, name='cutFile'),
    path('cutFile/', views.cutFile, name='cutFile'),
    path('pasteFile/<int:disk_id>/<int:catalog_id>/', views.pasteFile, name='pasteFile'),
    path('pasteFile/', views.pasteFile, name='pasteFile'),
    path('shareFile/', views.shareFile, name='shareFile'),
    path('shareFile/<int:file_id>/', views.shareFile, name='shareFile'),
    path('stopSharing/<int:file_id>/', views.stopSharing, name='stopSharing'),
    path('stopSharing/', views.stopSharing, name='stopSharing'),
    path('startSharing/', views.startSharing, name='startSharing'),
    path('startSharing/<int:file_id>/', views.startSharing, name='startSharing'),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dysk.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/dysk/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.template import Context, Template
from django.core.validators import FileExtensionValidator


class Dysk(models.Model):
    id_dysku = models.IntegerField(default=0)
    rozmiar_calkowity = models.IntegerField(default=0)
    rozmiar_zajety = models.IntegerField(default=0)
    id_user = models.ForeignKey(User, on_delete=models.CASCADE)

    @property
    def calculate(self):
        return (self.rozmiar_zajety * 100)/(self.rozmiar_calkowity*1000)

    def update_size(self, file_size):
        if self.rozmiar_zajety + file_size < self.rozmiar_calkowity * 1000:
            self.rozmiar_zajety += file_size
            self.save()
            return True
        else:
            return False

class Katalog(models.Model):
    id_katalogu = models.IntegerField(default=0)
    nazwa = models.CharField(max_length=200)
    id_dysku = models.ForeignKey(Dysk, on_delete=models.CASCADE)
    sciezka_do_katalogu = models.CharField(max_length=200)
    id_katalogu_nadrzednego = models.ForeignKey('self', on_delete=models.SET_NULL, blank=True, null=True)


class Plik(models.Model):
    id_pliku = models.IntegerField(default=0)
    nazwa = models.CharField(max_length=200)
    id_katalogu = models.ForeignKey(Katalog, on_delete=models.CASCADE)
    typ_pliku = models.CharField(max_length=200)
    sciezka_do_pliku = models.CharField(max_length=200)


class Document(models.Model):
    id_dokumentu = models.IntegerField(default=0)
    id_katalogu = models.ForeignKey(Katalog, on_delete=models.CASCADE, default=0)
    name = models.CharField(max_length=255, default='Document_name')
    typ_pliku = models.CharField(max_length=200,default="*")
    sciezka_do_pliku = models.CharField(max_length=200,default="/")
    udostepnienie = models.BooleanField(default=False)
    myfile = models.FileField(validators=[
        FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'ppt', 'xlsx', 'txt', 'jpg', 'png'])
    ])

    def __str__(self):
        return self.name



# class SharedDocument(models.Model):
#     id_dokumentu=models.ForeignKey(Document, on_delete=models.CASCADE, default=0)
#     udostepniony=models.

class Widok(models.Model):
    id_widoku = models.IntegerField(default=0)
    nazwa = models.CharField(max_length=255,default="*")
    tresc = models.TextField(default='Text sample')

class SchowekPlik(models.Model):
    id_schowka = models.IntegerField(default=0)
    id_pliku = models.ForeignKey(Document, on_delete=models.CASCADE, default=0)
    id_user = models.ForeignKey(User, on_delete=models.CASCADE)
    wycinanie = models.BooleanField(default=False)

mysite/templates/pages/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}About{% endblock %}

{% block content %}

<div class="bg-image hover-zoom" style="background-image: url({% static 'foto/strzalki.png'%}); height: 95vh; background-size: cover;
 background-repeat: no-repeat; margin-top: -5vh; overflow: hidden;">
<!--    <div class="mask w-100 h-100" style="background: linear-gradient(-->
<!--        45deg,-->
<!--        rgba(29, 236, 197, 0.5),-->
<!--        rgba(91, 14, 214, 0.5) 100%-->
<!--      );">-->
    <div class="w-100 text-center d-flex">
        <div class="w-50"></div>
<div class="w-100 text-center">
    <h1 style="font-family: 'Bebas Neue', cursive; letter-spacing: 5px; font-size:18vh;" class="w-100 text-primary display-1 mt-5">E-disc</h1>
      <h2 style="font-family: 'Bebas Neue', cursive; letter-spacing: 5px;" class="w-100 text-primary display-1 mt-5 ">Your virtual file folder</h2>
    <h3 style="font-family: 'Bebas Neue', cursive; letter-spacing: 5px;" class="h3 mt-2 mb-3 fw-normal "><strong>A place where you can put your files </strong></h3>
        <h3 style="font-family: 'Bebas Neue', cursive; letter-spacing: 5px;" class="h3 mt-2 mb-3 fw-normal "><strong>wherever you are,</strong></h3>
    <h3 style="font-family: 'Bebas Neue', cursive; letter-spacing: 5px;" class="h3 mt-2 mb-3 fw-normal "><strong>at any time.</strong></h3>


</div></div></div>
{% endblock %}

mysite/templates/pages/catalog.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Profile{% endblock %}

{% block content %}
{% if user.is_authenticated %}
{% ifequal disk.id_user|stringformat:"s" user.get_username %}

<script>console.log("xxx");</script>

<div class="d-flex fixed-top" style="margin-top: 56px;">
    <div class="d-flex flex-column p-3 text-white  bg-dark" style="width: 280px; height: 100vh;">

        <p class="fs-4 d-flex  align-items-center mx-3 mb-md-0 me-md-auto text-white text-decoration-none">
            Disk {{disk.id}}
        </p>

        <hr>
        <ul class=" nav nav-pills flex-column mb-auto">
            <br>
            <li class="w-100 nav-item">
                <p class="fs-5 align-items-center mx-3 mb-md-3 me-md-auto text-white text-decoration-none">
                    Add folder
                </p>
                <form role="form" method="get" action="{% url 'addCatalogNadrzedny' %}{{disk.id}}/{{catalog.id}}">
                    <input type="text" name="folder" class="w-100 border-primary form-control" placeholder="Folder name"
                           id="folder">
                    <div class="mt-2 ml-r w-100"><input class="btn btn-primary" type="submit" value="Add folder"></div>

                </form>
            </li>
            <br>
            <li class="w-100 nav-item">
                <svg class="bi me-2" width="40" height="32"></svg>
                <p class="fs-5 align-items-center mx-3 mb-md-0 me-md-auto text-white text-decoration-none">
                    Upload file
                </p>
                <form method="post" enctype="multipart/form-data" action="{% url 'upload' %}{{disk.id}}/{{catalog.id}}/">
                    {% csrf_token %}

                    <p class="d-none"><label for="id_id_katalogu">Id katalogu:</label> <select name="id_katalogu" id="id_id_katalogu">
                        <option value={{catalog.id}}>Katalog object {{catalog.id}}</option>
                    </select></p>
                    <p><label for="id_myfile"></label> <input type="file" name="myfile" required="" id="id_myfile"></p>

                    <button class="nav-link active" type="submit"> <img src="{% static 'foto/upload2.png'%}" width="20" height="20"> Upload</button>
                </form>
                {% if uploaded_file_url %}
                <p class="text-white">File uploaded</p>
                {% endif %}
<!--                <svg class="bi me-2" width="40" height="32"></svg>-->
<!--                <a href="{% url 'upload' %}{{disk.id}}/{{catalog.id}}" class="nav-link active">-->
<!--                    <img src="{% static 'foto/upload2.png'%}" width="20" height="20"> Upload </a>-->
            </li>
            <br>
            <li class="nav-item">
                <svg class="bi me-2" width="40" height="32"></svg>
                <p class="fs-5 align-items-center mx-3 mb-md-3 me-md-auto text-white text-decoration-none">
                    Paste file
                </p>

                <a href="{% url 'pasteFile' %}{{disk.id}}/{{catalog.id}}" class="nav-link active">
                    <img src="{% static 'foto/paste2.png'%}" width="20" height="20"> Paste file </a>
            </li>
        </ul>
    </div>
    <div class="w-100" style="margin-left: 20px; margin-right: 20px;">
        <br>
        <h5><a href="{% url 'profile' %}" style="text-decoration: none; color: black;"> Profile </a>
            || <a href="{% url 'disk' %}{{disk.id}}" style="text-decoration: none; color: black;"> Disk {{disk.id}} </a>
            {% if catalog.nazwa != "root" %}
            <!--           {% if request.get_full_path != "/disk/66/" %}-->
            <!--           {% endif %}-->
            || <a href="{% url 'catalog' %}{{disk.id}}/{{catalog.id}}" style="text-decoration: none; color: black;">
                Catalog {{catalog.id}}</a>

            {% endif %}

        </h5>
        <br>
        <table class="w-100" cellspacing='0' cellpadding='5' border-spacing='5'
               style="margin:0;padding:0;border: 1px solid black;">
            <tr style="border: 1px solid black;">
                <th style="border: 1px solid black;text-align:center;">Name</th>
                <th style="border: 1px solid black;text-align:center;">Copy</th>
                <th style="border: 1px solid black;text-align:center;">Share</th>
                <th style="border: 1px solid black;text-align:center;">Size</th>
                <th style="border: 1px solid black;text-align:center;">Delete</th>
            </tr>
            {% for sub_catalog in sub_catalogs %}

            <tr style="border: 1px solid black;">
                <th style="border: 1px solid black;">
                    <div class="d-flex  justify-content-between">
                        <a style="margin-top:5px;" href="{% url 'catalog' %}{{disk.id}}/{{sub_catalog.id}}">
                            <img src="{% static 'foto/folder2.png'%}" width="25" height="25">
                            {{sub_catalog.nazwa}}
                        </a>

                        <!--                <button id="btn">...</button>-->
                        <form role="form" method="get"
                              action="{% url 'changeNameFolder' %}{{disk.id}}/{{sub_catalog.id}}">
                            <div class="w-100 d-flex  justify-content-between">
                                <input style="margin-right:10px;" type="text" name="changeFolder"
                                       class="w-100 border-primary form-control" placeholder="Update folder name"
                                       id="changeFolder">
                                <input class="btn btn-primary" type="submit" value="Update">
                            </div>
                        </form>
                    </div>
                </th>
                <th style="border: 1px solid black;"></th>
                <th style="border: 1px solid black;"></th>
                <th style="border: 1px solid black;"></th>
                <th style="border: 1px solid black;text-align:center;"><a
                        href="{% url 'deleteCatalog' %}{{sub_catalog.id}}">
                    <img src="{% static 'foto/delete2.png'%}" width="25" height="25">
                </a></th>
            </tr>
            {% endfor %}


            {% for file in files %}
            <tr style="border: 1px solid black;">
                <th style="border: 1px solid black;">
                    <a href="{{file.myfile.url}}" download> <img src="{% static 'foto/file2.png'%}" width="25"
                                                                 height="25"> {{file.myfile.name}} </a>
                </th>
                <th style="border: 1px solid black;text-align:center;">
                    <a href="{% url 'copyFile' %}{{catalog.id}}/{{file.id}}">
                        <img src="{% static 'foto/copy2.png'%}" width="20" height="20"></a>
                    <a href="{% url 'cutFile' %}{{catalog.id}}/{{file.id}}">
                        <img src="{% static 'foto/cut2.png'%}" width="20" height="20"></a>
                </th>
                <th style="border: 1px solid black;text-align:center;">
                    {% if file.udostepnienie is True%}
                    <div class="w-100 d-flex  justify-content-between">
                        <a style="margin-top:5px;" href="{% url 'stopSharing'%}{{file.id}}">
                            Stop sharing
                        </a>
                        <br>
                        <div class="d-flex align-self-center"><p id="copy" style="margin-top:5px;margin-right:10px;margin-bottom:0; padding:5.5px;" class="align-self-center alert-primary">http://165.227.165.148{% url 'shareFile'%}{{file.id}}</p>
                        </div>
                    </div>
                    {% else %}
                    <img src="{% static 'foto/outline_share_black_24dp.png'%}" width="25" height="25"><a
                        href="{% url 'startSharing'%}{{file.id}}">
                    Share
                </a>
                    {% endif %}
                </th>
                <th style="border: 1px solid black;text-align:center;">
                    <div class="d-inline-block" style="width:40px; height: 40px;"><canvas id="{{file.myfile.size}}" ></canvas> {{file.myfile.size}}B</div>
                </th>
                <th style="border: 1px solid black;text-align:center;"><a href="{% url 'deleteFile' %}{{file.id}}">
                    <img src="{% static 'foto/delete2.png'%}" width="25" height="25">
                </a></th>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% else %}
<h4>ACCESS DENIED</h4>
{% endifequal %}
{% else %}
<h4>You are not logged in</h4>
{% endif %}
   <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.3.2/chart.min.js" integrity="sha512-VCHVc5miKoln972iJPvkQrUYYq7XpxXzvqNfiul1H4aZDwGBGC0lq373KNleaB2LpnC2a/iNfE5zoRYmB4TRDQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="{% static 'js/share.js'%}"></script>
<script src="{% static 'js/catalog_charts.js'%}"></script>
{% endblock %}

mysite/templates/pages/disk.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}
{% if user.is_authenticated %}
    {% ifequal disk.id_user|stringformat:"s" user.get_username %}
        <br>
        <table cellspacing='0' cellpadding='5' border-spacing='5' style="margin:0;padding:0;border: 1px solid black;">
            <tr style="border: 1px solid black;">
                <th style="border: 1px solid black;text-align:center;">Name</th>
                <th style="border: 1px solid black;text-align:center;">Size</th>
                <th style="border: 1px solid black;text-align:center;">Delete</th>
            </tr>
            {% for sub_catalog in sub_catalogs %}
            <tr style="border: 1px solid black;">
            <th style="border: 1px solid black;"><a href="{% url 'catalog' %}{{disk.id}}/{{sub_catalog.id}}">
                <img src="{% static 'foto/folder2.png'%}" width="25" height="25">
                {{sub_catalog.nazwa}}
            </a></th>
            <th style="border: 1px solid black;"> </th>
            <th style="border: 1px solid black;text-align:center;"><a href="{% url 'deleteCatalog' %}{{sub_catalog.id}}">
                <img src="{% static 'foto/delete2.png'%}" width="25" height="25">
            </a></th>
            </tr>
            {% endfor %}


        {% for file in files %}
            <tr style="border: 1px solid black;">
                <th style="border: 1px solid black;">
                    <a  href = "{{file.myfile.url}}" download> <img src="{% static 'foto/file2.png'%}" width="25" height="25"> {{file.myfile.name}}   </a>
                </th>
                <th style="border: 1px solid black;text-align:center;">
                     {{file.myfile.size}}B
                </th>
                <th style="border: 1px solid black;text-align:center;"> <a href="{% url 'deleteFile' %}{{file.id}}">
                <img src="{% static 'foto/delete2.png'%}" width="25" height="25">
            </a> </th>
            </tr>
        {% endfor %}
        </table>
    {% else %}
    <h4>ACCESS DENIED</h4>
    {% endifequal %}
{% else %}
      <h4>You are not logged in</h4>
{% endif %}
{% endblock %}

mysite/templates/pages/error.html
{% extends 'base.html' %}
{% load static %}

{% block title %}About{% endblock %}

{% block content %}

<div class="bg-image hover-zoom" style="background-image: url({% static 'foto/strzalki.png'%}); height: 95vh; background-size: cover;
 background-repeat: no-repeat; margin-top: -5vh; overflow: hidden;">
<!--    <div class="mask w-100 h-100" style="background: linear-gradient(-->
<!--        45deg,-->
<!--        rgba(29, 236, 197, 0.5),-->
<!--        rgba(91, 14, 214, 0.5) 100%-->
<!--      );">-->
    <div class="w-100 text-center d-flex">
        <div class="w-50"></div>
<div class="w-100 text-center">
    <h1 style="font-family: 'Bebas Neue', cursive; letter-spacing: 5px; font-size:18vh;" class="w-100 text-primary display-1 mt-5">Sorry...</h1>
      <h2 style="font-family: 'Bebas Neue', cursive; letter-spacing: 5px;" class="w-100 text-primary display-1 mt-5 ">Something went wrong :(</h2>
</div></div></div>
{% endblock %}

mysite/templates/pages/index.html
<!-- templates/index.html-->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  <br>
  <h4>Hi {{ user.username }}!</h4>
  <br>
  <a href="{% url 'profile' %}">  Go to your profile  </a>
  <!--<p><a href="{% url 'logout' %}">Log Out</a></p>-->
{% else %}
  <p class="mt-4 text-center">You are not logged in</p>
  <p class="text-center" ><a class="btn btn-outline-primary" href="{% url 'login' %}">Log In</a>
  <a class="btn btn-outline-primary" href="{% url 'signup' %}">Sign Up</a></p>
{% endif %}
{% endblock %}

mysite/templates/pages/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Profile{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<div class="d-flex">
    <br>
    <div class="d-flex flex-column p-3 text-white  bg-dark fixed-top" style="width: 280px; height: 100vh; margin-top: 56px;">
    <p class="fs-4 d-flex  align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
      {{view1.tresc}}
    </p>
        <hr>
    <ul class="nav nav-pills flex-column mb-auto">
        <br>
      <li class="nav-item">
    <a href="{% url 'addStandard' %}/{{user.id}}" class="nav-link active"><img src="{% static 'foto/add2.png'%}" width="20" height="20">    New disk  1KB</a>
      </li></ul>
    </div>
    <div class="w-100 text-center" style="margin-left: 300px; margin-right: 20px;">
    <br>
    <h4 style="width: 100%" >{{view2.tresc}}</h4>
    <br>
    <table class="w-100" cellspacing='0' cellpadding='20' border-spacing='5' style="margin:0;padding:0;border: 1px solid black;">
        <tr style="border: 1px solid black;">
            <th style="border: 1px solid black;text-align:center;">Disk id</th>
            <th style="border: 1px solid black;text-align:center;">Disk usage</th>
            <th style="border: 1px solid black;text-align:center;">Delete</th>
        </tr>
        {% for object in all_objects %}
        {% ifequal object.id_user|stringformat:"s" user.get_username %}
        <tr style="border: 1px solid black;">
            <th style="border: 1px solid black;">
                {% ifequal object.rozmiar_calkowity 5 %}
                    <img src="{% static 'foto/star2.png'%}" width="20" height="20">
                {% endifequal%}
                <a href="{% url 'disk' %}{{object.id}}">
                <img src="{% static 'foto/hdd2.png'%}" width="25" height="25">
                {{object.id}}  </a></th>
            <th style="border: 1px solid black;text-align:center;">
                <div class="d-inline-block" style="width:40px; height: 40px;"><canvas id="{{object.calculate}}" ></canvas> {{object.calculate}}%</div></th>
            <th style="border: 1px solid black;text-align:center;"><a href="{% url 'diskDelete' %}{{object.id}}">
            <img src="{% static 'foto/delete2.png'%}" width="25" height="25">
            </a></th>
        </tr>
        {% endifequal %}
    {% endfor %}
    </table>
    </div></div>
{% else %}
<div class="d-flex ">
<img style="height:85vh;" class="img-responsive" src="{% static 'foto/ludzik.jpg'%}" >
    <div class="w-100 text-center">
      <h1 style="font-family: 'Bebas Neue', cursive; letter-spacing: 5px;" class="w-100 text-primary display-1 mt-2 ">Your virtual file folder</h1>
    <main class="form-signing">
    <form method="post">

    <h1 style="margin-top: 7vh;" class="h3 mt-2 mb-3 fw-normal "><strong>Create an account</strong></h1>

{% csrf_token %}
        <p style="height: 50px;">
            <input style="height: 50px;margin-left: auto;margin-right: auto;" class="w-25 border-primary form-control" type="text" name="username" maxlength="150" autocapitalize="none" autocomplete="username" placeholder="Username" autofocus="" required="" id="id_username">
        </p>
        <p style="height: 50px;">
            <input style="height: 50px;margin-left: auto;margin-right: auto;" class="w-25 border-primary form-control" type="email" name="email" maxlength="150" autocapitalize="none" autocomplete="email" placeholder="Email" autofocus="" required="" id="id_email">
        </p>
        <p>
            <input style="height: 50px;margin-left: auto;margin-right: auto;" class="w-25 border-primary form-control" type="password" name="password1" autocomplete="new-password" placeholder="Password" required="" id="id_password1">

        </p>
        <p style="font-size: 12px; margin-top: -15px;">Your password must contain at least 8 characters.</p>
        <p>
            <input style="height: 50px;margin-left: auto;margin-right: auto;" class="w-25 border-primary form-control" type="password" name="password2" autocomplete="new-password" placeholder="Confirm the password" required="" id="id_password2">
        <p style="margin-top: -15px;font-size: 12px;" class="helptext">Enter the same password as before, for verification.</p>
        </p>
    <button class="w-25 btn btn-lg btn-primary" type="submit">Sign up</button>

  </form>
</main>
        <br>
       <p >Or, if you already have an account</p>
        <p class="text-center" ><a class="w-25 btn btn-lg btn-primary mb-5" href="{% url 'login' %}">Log In</a>
    </div>

</div>
{% endif %}
 <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.3.2/chart.min.js" integrity="sha512-VCHVc5miKoln972iJPvkQrUYYq7XpxXzvqNfiul1H4aZDwGBGC0lq373KNleaB2LpnC2a/iNfE5zoRYmB4TRDQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="{% static 'js/profile_charts.js'%}"></script>
{% endblock %}

mysite/templates/pages/shareFile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Share File{% endblock %}

{% block content %}
{% if file.udostepnienie is True %}
<div class="bg-image hover-zoom" style="background-image: url({% static 'foto/strzalki.png'%}); height: 95vh; background-size: cover;
 background-repeat: no-repeat; margin-top: -5vh; overflow: hidden;">
<div class="text-center">
    <br>
<p style="letter-spacing: 2px; font-size:3rem; margin-top: 30vh;">{{file.myfile.name}}</p>
    <a  href = "{{file.myfile.url}}" download ><button class="btn btn-primary"><i class="fa fa-download"></i> Download</button></a>
<br>
    <br>
</div>
</div>
{% else %}
<p>Brak pliku</p>
{% endif %}
<script src="{% static 'js/share.js'%}"></script>
{% endblock %}

mysite/templates/pages/size_error.html
{% extends 'base.html' %}
{% load static %}

{% block title %}About{% endblock %}

{% block content %}

<div class="bg-image hover-zoom" style="background-image: url({% static 'foto/strzalki.png'%}); height: 95vh; background-size: cover;
 background-repeat: no-repeat; margin-top: -5vh; overflow: hidden;">
<!--    <div class="mask w-100 h-100" style="background: linear-gradient(-->
<!--        45deg,-->
<!--        rgba(29, 236, 197, 0.5),-->
<!--        rgba(91, 14, 214, 0.5) 100%-->
<!--      );">-->
    <div class="w-100 text-center d-flex">
        <div class="w-50"></div>
<div class="w-100 text-center">
    <h1 style="font-family: 'Bebas Neue', cursive; letter-spacing: 5px; font-size:18vh;" class="w-100 text-primary display-1 mt-5">Sorry...</h1>
      <h2 style="font-family: 'Bebas Neue', cursive; letter-spacing: 5px;" class="w-100 text-primary display-1 mt-5 ">This file is too big :(</h2>
</div></div></div>
{% endblock %}

mysite/templates/pages/upload.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <p class="d-none" ><label for="id_id_katalogu">Id katalogu:</label> <select name="id_katalogu" id="id_id_katalogu">
  <option value={{catalog.id}}>Katalog object {{catalog.id}}</option>
</select></p>
<p><label for="id_myfile"></label> <input type="file" name="myfile" required="" id="id_myfile"></p>
    <input type="submit" value="Upload">
</form>
    {% if uploaded_file_url %}
    <p>File uploaded</p>
    {% endif %}
{% endblock %}